# -*- coding: utf-8 -*-
"""Boosting heart .csv .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZBTCInUs_KWXrvCNlTbiKfn0rvbRnwA
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report

# For XGBoost
from xgboost import XGBClassifier

df = pd.read_csv("Heart.csv")

df.head()

# Drop unnecessary column if exists (like index column)
if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'])

# Convert categorical variables using one-hot encoding
df = pd.get_dummies(df, drop_first=True)

df.head()

X = df.drop('AHD_Yes', axis=1)   # Target column (Heart disease Yes/No)
y = df['AHD_Yes']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

tree_values = [20, 50, 100, 200, 500]

rf_results = {}

for n in tree_values:
    rf = RandomForestClassifier(n_estimators=n, random_state=42)
    rf.fit(X_train, y_train)

    y_pred = rf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    rf_results[n] = acc
    print(f"Trees: {n}, Accuracy: {acc:.4f}")

best_n = max(rf_results, key=rf_results.get)

rf_best = RandomForestClassifier(n_estimators=best_n, random_state=42)
rf_best.fit(X_train, y_train)

y_pred = rf_best.predict(X_test)

print("Best Number of Trees:", best_n)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

import numpy as np

# Identify columns with NaNs in X_train and impute them
# It's crucial to use the mean from X_train to impute both X_train and X_test

nan_cols = X_train.columns[X_train.isnull().any()].tolist()
if nan_cols:
    print(f"NaNs found in X_train columns: {nan_cols}. Imputing with mean...")
    for col in nan_cols:
        mean_val = X_train[col].mean()
        X_train[col].fillna(mean_val, inplace=True)
        X_test[col].fillna(mean_val, inplace=True)
else:
    print("No NaNs found in X_train.")

ada = AdaBoostClassifier(n_estimators=100, random_state=42)
ada.fit(X_train, y_train)

y_pred_ada = ada.predict(X_test)

ada_acc = accuracy_score(y_test, y_pred_ada)

print("AdaBoost Accuracy:", ada_acc)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_ada))

xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

xgb_acc = accuracy_score(y_test, y_pred_xgb)

print("XGBoost Accuracy:", xgb_acc)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_xgb))

print("🔹 Model Comparison:\n")

for n, acc in rf_results.items():
    print(f"Random Forest ({n} trees): {acc:.4f}")

print(f"\nAdaBoost Accuracy: {ada_acc:.4f}")
print(f"XGBoost Accuracy: {xgb_acc:.4f}")





