# -*- coding: utf-8 -*-
"""lemmatization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKjrdkoUKC5fZLcru1B0HUdKc4P96AlC
"""

A #a program to implement  mordern subword tokenization with hugging face transformer

!pip install transformers

from transformers import AutoTokenizer

bert_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

gpt_tokenizer = AutoTokenizer.from_pretrained("gpt2")

text = "The State-of-the-art processor utilizes advanced machine learning algorithm smoothly"

print("===BERT TOKENIZER===")
bert_tokens = bert_tokenizer.tokenize(text)
bert_ids = bert_tokenizer.convert_tokens_to_ids(bert_tokens)

print("Tokens:", bert_tokens)
print("Token IDs:", bert_ids)

print("\n=== GPT-2 Tokenizer ===")
gpt_tokens = gpt_tokenizer.tokenize(text)
gpt_ids = gpt_tokenizer.convert_tokens_to_ids(gpt_tokens)

print("Tokens:", gpt_tokens)
print("Token IDs:", gpt_ids)



# B . Program to implement lemmatization

import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('omw-1.4')

sentence = "The State-of-the-art processor utilizes advanced machine learning algorithm smoothly"
lemmatizer = WordNetLemmatizer()
tokens = word_tokenize(sentence)
tokens = word_tokenize(sentence)

print("Original\t\t\tLemma")
print("-----------------------------------------")
for token in tokens:
    if token.isalpha():
        lemma = lemmatizer.lemmatize(token)
        print(f"{token}\t\t\t{lemma}")

