# -*- coding: utf-8 -*-
"""malaria 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1heDMftl50P9HF9qHVN-cKOBkpeJ0wCld
"""

!pip install -q kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d iarunava/cell-images-for-detecting-malaria
!ls

!file "/content/archive (2).zip"

!ls /content



import zipfile

with zipfile.ZipFile("cell-images-for-detecting-malaria.zip", "r") as zip_ref:
    zip_ref.extractall("/content/malaria_dataset")

print("Done")

"""# Data Understanding"""

import os

print(os.listdir("/content/malaria_dataset"))

import os

print(os.listdir("/content/malaria_dataset/cell_images"))

print("Total Images:", len(dataset))

#total number of classes
from torchvision.datasets import ImageFolder

dataset = ImageFolder("/content/malaria_dataset/cell_images")

print("Classes:", dataset.classes)
print("Number of Classes:", len(dataset.classes))

#image per class
import os

dataset_path = "/content/malaria_dataset/cell_images"

for cls in os.listdir(dataset_path):
    class_path = os.path.join(dataset_path, cls)

    if os.path.isdir(class_path):
        print(f"{cls}: {len(os.listdir(class_path))} images")

import os

parasitized = len(os.listdir("/content/malaria_dataset/cell_images/Parasitized"))
uninfected = len(os.listdir("/content/malaria_dataset/cell_images/Uninfected"))

print("Parasitized:", parasitized)
print("Uninfected:", uninfected)

import os

for root, dirs, files in os.walk("/content/malaria_dataset"):
    print(root)
    print("Folders:", dirs)
    print("-"*50)

print(os.listdir("/content/malaria_dataset/cell_images/cell_images"))



import matplotlib.pyplot as plt
from PIL import Image
import random
import os

dataset_path = "/content/malaria_dataset/cell_images"

classes = ["Parasitized", "Uninfected"]

plt.figure(figsize=(10,5))

for i, cls in enumerate(classes):

    images = os.listdir(os.path.join(dataset_path, cls))

    img_name = random.choice(images)

    img_path = os.path.join(dataset_path, cls, img_name)

    img = Image.open(img_path)

    plt.subplot(1,2,i+1)
    plt.imshow(img)
    plt.title(cls)
    plt.axis("off")

plt.show()

dataset_path = "/content/malaria_dataset/cell_images"

for folder in os.listdir(dataset_path):

    folder_path = os.path.join(dataset_path, folder)

    if os.path.isdir(folder_path):

        print(folder, ":", len(os.listdir(folder_path)))

"""# Image Preprocessing, Augmentation and Dataset Splitting"""

from torchvision import transforms

train_transform = transforms.Compose([

    transforms.Resize((224,224)),

    transforms.RandomHorizontalFlip(),

    transforms.RandomRotation(10),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

test_transform = transforms.Compose([

    transforms.Resize((224,224)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

from torchvision.datasets import ImageFolder

dataset = ImageFolder(
    root="/content/malaria_dataset/cell_images",
    transform=train_transform
)

print("Classes:", dataset.classes)
print("Total Images:", len(dataset))

import matplotlib.pyplot as plt
from PIL import Image
import random
import os
                                                                 #displaying a few samples
classes = ["Parasitized", "Uninfected"]

plt.figure(figsize=(8,4))

for i, cls in enumerate(classes):

    img_name = random.choice(os.listdir(os.path.join(dataset_path, cls)))
    img_path = os.path.join(dataset_path, cls, img_name)

    img = Image.open(img_path)

    plt.subplot(1,2,i+1)
    plt.imshow(img)
    plt.title(cls)
    plt.axis("off")

plt.show()

from PIL import Image
import os

sample_img = Image.open(img_path)

print("Image Size:", sample_img.size)
print("Image Mode:", sample_img.mode)

import matplotlib.pyplot as plt
from PIL import Image
import random
import os
import torch

# Select a random image
dataset_path = "/content/malaria_dataset/cell_images"

class_name = random.choice(["Parasitized", "Uninfected"])
img_name = random.choice(os.listdir(os.path.join(dataset_path, class_name)))

img_path = os.path.join(dataset_path, class_name, img_name)

# Original Image
original_img = Image.open(img_path).convert("RGB")

# Apply transformations
transformed_img = train_transform(original_img)

# Convert tensor back to image for visualization
img_display = transformed_img.permute(1, 2, 0).numpy()

# Undo normalization for display
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]

img_display = img_display * std + mean
img_display = img_display.clip(0, 1)

# Plot
plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.imshow(original_img)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(img_display)
plt.title("After Preprocessing")
plt.axis("off")

plt.show()                                    #no such difference from human POV

#Show Multiple Augmented Versions
import matplotlib.pyplot as plt
from PIL import Image
import random
import os

dataset_path = "/content/malaria_dataset/cell_images"

class_name = random.choice(["Parasitized", "Uninfected"])
img_name = random.choice(os.listdir(os.path.join(dataset_path, class_name)))

img_path = os.path.join(dataset_path, class_name, img_name)

img = Image.open(img_path).convert("RGB")

plt.figure(figsize=(15,5))

for i in range(5):

    aug_img = train_transform(img)

    aug_img = aug_img.permute(1,2,0).numpy()

    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]

    aug_img = aug_img * std + mean
    aug_img = aug_img.clip(0,1)

    plt.subplot(1,5,i+1)
    plt.imshow(aug_img)
    plt.axis("off")
    plt.title(f"Aug {i+1}")

plt.suptitle("Data Augmentation Examples")
plt.show()

"""### Create Dataset and DataLoaders"""

from torchvision.datasets import ImageFolder

dataset = ImageFolder(
    root="/content/malaria_dataset/cell_images",
    transform=train_transform
)

print("Classes:", dataset.classes)
print("Total Images:", len(dataset))

from torch.utils.data import random_split
import torch

torch.manual_seed(42)

train_size = int(0.7 * len(dataset))
val_size = int(0.15 * len(dataset))
test_size = len(dataset) - train_size - val_size

train_dataset, val_dataset, test_dataset = random_split(
    dataset,
    [train_size, val_size, test_size]
)

print("Train:", len(train_dataset))
print("Validation:", len(val_dataset))
print("Test:", len(test_dataset))

from torch.utils.data import DataLoader

batch_size = 32

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False
)

print("DataLoaders Created Successfully!")

images, labels = next(iter(train_loader))

print("Image Batch Shape:", images.shape)
print("Label Batch Shape:", labels.shape)

"""ResNet18
      ↓
Train on Clean Dataset
      ↓
Validation
      ↓
Save Best Model
      ↓
Test Accuracy
"""

#Dataset Preparation ✅
        #↓
#Baseline CNN (ResNet18) ← NEXT
        #↓
#Evaluate Clean Accuracy
        #↓
#Backdoor Attack

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)



