# -*- coding: utf-8 -*-
"""stemming basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOkZAjLsA2i3UPltoPWbaIOKheWYlKHT
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.stem import SnowballStemmer
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import MWETokenizer

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('omw-1.4')

text = "The State-of-the-art processor utilizes advanced machine learning algorithm smoothly"

tokens = word_tokenize(text.lower())

print("=== Standard Tokenization ===")
print(tokens)

mwe_tokenizer = MWETokenizer(
    [
        ("state", "of", "the", "art"),
        ("machine", "learning")
    ],
    separator="_"
)

mwe_tokens = mwe_tokenizer.tokenize(tokens)

print("\n=== Multi-word Expression Tokenization ===")
print(mwe_tokens)

stemmer = SnowballStemmer("english")

print("\n=== Snowball Stemming ===")

for token in mwe_tokens:
    stem = stemmer.stem(token)
    print(f"{token:25} -> {stem}")

lemmatizer = WordNetLemmatizer()

print("\n=== Lemmatization ===")

for token in mwe_tokens:
  if token.isalpha():
    lemma = lemmatizer.lemmatize(token)
    print(f"{token:25} -> {lemma}")

print("\n=== Required Lemmatization ===")

print("algorithms ->",
      lemmatizer.lemmatize("algorithms", pos="n"))

print("utilizes   ->",
      lemmatizer.lemmatize("utilizes", pos="v"))

